import 'spoken.dart';

/// Support code shown to the waiter (12 §2.5, 13 · R02): the last 6
/// characters of the failed request's `X-Request-Id`, upper case, no
/// hyphens — `…-4b1e9c7f3a9c` → `7F3A9C`.
abstract final class SupportCode {
  /// Number of characters (12 §2.5).
  static const int length = 6;

  /// Support code for [requestId] (a UUID v4 generated by the app).
  ///
  /// Throws [FormatException] when fewer than 6 characters remain after
  /// removing hyphens.
  static String fromRequestId(String requestId) {
    final String compact = requestId.trim().replaceAll('-', '');
    if (compact.length < length) {
      throw FormatException(
        'X-Request-Id too short for a support code',
        requestId,
      );
    }
    return compact.substring(compact.length - length).toUpperCase();
  }

  /// Screen-reader form for the `{code}` of `common.supportCode.a11y`:
  /// characters read singly, `7F3A9C` → `7 F 3 A 9 C` (12 §2.5).
  static String spoken(String code) => Spoken.characters(code);
}
