<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\GiftCardStatus;
use App\Enums\NfcTagType;
use App\Models\Concerns\BelongsToRestaurant;
use App\Services\GiftCards\GiftCardService;
use Database\Factories\GiftCardFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * A gift card. The physical NFC tag / QR code only ever carries `public_token`
 * (a random UUID v4 inside a URL). Balance and all customer data live exclusively on the server.
 *
 * Mutations of monetary fields must go through {@see GiftCardService},
 * which performs them atomically under a row lock and writes the ledger entry.
 *
 * @property string $id
 * @property string $restaurant_id
 * @property string|null $customer_id
 * @property string $public_token
 * @property string $card_number
 * @property GiftCardStatus $status
 * @property string $currency
 * @property int $initial_value
 * @property int $balance
 * @property int $total_loaded
 * @property int $total_redeemed
 * @property Carbon|null $expires_at
 * @property Carbon|null $activated_at
 * @property Carbon|null $redeemed_at
 * @property Carbon|null $blocked_at
 * @property string|null $blocked_reason
 * @property Carbon|null $expired_at
 * @property string|null $replaced_by_id
 * @property string|null $replaces_id
 * @property string|null $issued_by
 * @property string|null $recipient_name
 * @property string|null $notes
 * @property NfcTagType|null $nfc_tag_type
 * @property string|null $nfc_uid
 * @property Carbon|null $nfc_written_at
 * @property Carbon|null $nfc_verified_at
 * @property-read string|null $nfc_uid_active Generated: the UID while the card is usable (UNIQUE).
 * @property bool $nfc_locked
 * @property int|null $nfc_read_counter
 * @property Carbon|null $last_used_at
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property-read Restaurant $restaurant
 * @property-read Customer|null $customer
 * @property-read User|null $issuer
 * @property-read GiftCard|null $replacedBy
 * @property-read GiftCard|null $replaces
 */
class GiftCard extends Model
{
    use BelongsToRestaurant;

    /** @use HasFactory<GiftCardFactory> */
    use HasFactory;

    use HasUuids;
    use SoftDeletes;

    /**
     * Monetary and state columns are deliberately NOT fillable: they may only be changed by the service layer.
     */
    protected $fillable = ['customer_id', 'recipient_name', 'notes', 'expires_at'];

    protected $hidden = ['nfc_read_counter', 'nfc_uid_active'];

    protected function casts(): array
    {
        return [
            'status' => GiftCardStatus::class,
            'nfc_tag_type' => NfcTagType::class,
            'initial_value' => 'integer',
            'balance' => 'integer',
            'total_loaded' => 'integer',
            'total_redeemed' => 'integer',
            'nfc_read_counter' => 'integer',
            'nfc_locked' => 'boolean',
            'expires_at' => 'datetime',
            'activated_at' => 'datetime',
            'redeemed_at' => 'datetime',
            'blocked_at' => 'datetime',
            'expired_at' => 'datetime',
            'nfc_written_at' => 'datetime',
            'nfc_verified_at' => 'datetime',
            'last_used_at' => 'datetime',
        ];
    }

    /**
     * Only the primary key is a UUID generated by Eloquent (time-ordered v7 for index locality);
     * the public token is a random v4 generated by the service.
     *
     * @return list<string>
     */
    public function uniqueIds(): array
    {
        return ['id'];
    }

    public function isExpiredByDate(?Carbon $now = null): bool
    {
        return $this->expires_at !== null && $this->expires_at->lessThanOrEqualTo($now ?? Carbon::now());
    }

    public function isUsable(): bool
    {
        return $this->status === GiftCardStatus::Active && ! $this->isExpiredByDate();
    }

    /** @return BelongsTo<Customer, $this> */
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    /** @return BelongsTo<User, $this> */
    public function issuer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'issued_by')->withTrashed();
    }

    /** @return BelongsTo<GiftCard, $this> */
    public function replacedBy(): BelongsTo
    {
        return $this->belongsTo(self::class, 'replaced_by_id');
    }

    /** @return BelongsTo<GiftCard, $this> */
    public function replaces(): BelongsTo
    {
        return $this->belongsTo(self::class, 'replaces_id');
    }

    /** @return HasMany<GiftCardTransaction, $this> */
    public function transactions(): HasMany
    {
        return $this->hasMany(GiftCardTransaction::class)->orderByDesc('created_at');
    }

    /**
     * @param  Builder<GiftCard>  $query
     * @return Builder<GiftCard>
     */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        if ($term === null || trim($term) === '') {
            return $query;
        }

        $term = trim($term);
        $digits = preg_replace('/\D+/', '', $term) ?? '';
        $like = '%'.addcslashes($term, '%_\\').'%';

        return $query->where(static function (Builder $q) use ($term, $digits, $like): void {
            if ($digits !== '') {
                $q->orWhere('card_number', 'like', '%'.$digits.'%');
            }
            $q->orWhere('recipient_name', 'like', $like)
                ->orWhere('notes', 'like', $like)
                ->orWhereHas('customer', static function (Builder $c) use ($term): void {
                    /** @var Builder<Customer> $c */
                    $c->search($term);
                });
        });
    }

    /**
     * @param  Builder<GiftCard>  $query
     * @return Builder<GiftCard>
     */
    public function scopeOutstanding(Builder $query): Builder
    {
        return $query->whereIn('status', [GiftCardStatus::Active->value, GiftCardStatus::Inactive->value, GiftCardStatus::Blocked->value]);
    }
}
