// GENERATED by tool/import_strings.dart — do not edit.
// Pseudo-localisation wrapper for AppLocalizations (09 §6.5).

import '../../l10n/app_localizations.dart';
import 'pseudo_transform.dart';

/// [AppLocalizations] whose every message is pseudo-localised
/// with [pseudoLocalize]; placeholder values are kept intact.
class PseudoAppLocalizations extends AppLocalizations {
  /// Wraps [base].
  PseudoAppLocalizations(this.base) : super(base.localeName);

  /// The real localizations being transformed.
  final AppLocalizations base;

  @override
  String get appName => pseudoLocalize(base.appName);

  @override
  String get commonCancel => pseudoLocalize(base.commonCancel);

  @override
  String get commonClose => pseudoLocalize(base.commonClose);

  @override
  String get commonBack => pseudoLocalize(base.commonBack);

  @override
  String get commonDone => pseudoLocalize(base.commonDone);

  @override
  String get commonTryAgain => pseudoLocalize(base.commonTryAgain);

  @override
  String get commonScanAgain => pseudoLocalize(base.commonScanAgain);

  @override
  String get commonTapAgain => pseudoLocalize(base.commonTapAgain);

  @override
  String get commonOpenSettings => pseudoLocalize(base.commonOpenSettings);

  @override
  String get commonBackToSignIn => pseudoLocalize(base.commonBackToSignIn);

  @override
  String get commonCheckAgain => pseudoLocalize(base.commonCheckAgain);

  @override
  String commonSupportCode(String code) =>
      pseudoLocalize(base.commonSupportCode(pseudoMarker(0)), <String>[code]);

  @override
  String commonSupportCodeA11y(String code) => pseudoLocalize(
    base.commonSupportCodeA11y(pseudoMarker(0)),
    <String>[code],
  );

  @override
  String get commonCopied => pseudoLocalize(base.commonCopied);

  @override
  String get redeemNothingBooked => pseudoLocalize(base.redeemNothingBooked);

  @override
  String get getManager => pseudoLocalize(base.getManager);

  @override
  String get splashLoading => pseudoLocalize(base.splashLoading);

  @override
  String get startupOfflineTitle => pseudoLocalize(base.startupOfflineTitle);

  @override
  String get startupOfflineBody => pseudoLocalize(base.startupOfflineBody);

  @override
  String get startupHostNotFoundTitle =>
      pseudoLocalize(base.startupHostNotFoundTitle);

  @override
  String startupHostNotFoundBody(String host) => pseudoLocalize(
    base.startupHostNotFoundBody(pseudoMarker(0)),
    <String>[host],
  );

  @override
  String get startupRefusedTitle => pseudoLocalize(base.startupRefusedTitle);

  @override
  String startupRefusedBody(String host) =>
      pseudoLocalize(base.startupRefusedBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupTimeoutTitle => pseudoLocalize(base.startupTimeoutTitle);

  @override
  String startupTimeoutBody(String host) =>
      pseudoLocalize(base.startupTimeoutBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupTlsTitle => pseudoLocalize(base.startupTlsTitle);

  @override
  String startupTlsBody(String host) =>
      pseudoLocalize(base.startupTlsBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupServerErrorTitle =>
      pseudoLocalize(base.startupServerErrorTitle);

  @override
  String startupServerErrorBody(String host, String status) => pseudoLocalize(
    base.startupServerErrorBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[host, status],
  );

  @override
  String get startupInvalidResponseTitle =>
      pseudoLocalize(base.startupInvalidResponseTitle);

  @override
  String startupInvalidResponseBody(String host) => pseudoLocalize(
    base.startupInvalidResponseBody(pseudoMarker(0)),
    <String>[host],
  );

  @override
  String get startupConfigurationTitle =>
      pseudoLocalize(base.startupConfigurationTitle);

  @override
  String get startupConfigurationBody =>
      pseudoLocalize(base.startupConfigurationBody);

  @override
  String get startupStorageTitle => pseudoLocalize(base.startupStorageTitle);

  @override
  String get startupStorageBody => pseudoLocalize(base.startupStorageBody);

  @override
  String get startupUnknownTitle => pseudoLocalize(base.startupUnknownTitle);

  @override
  String get startupUnknownBody => pseudoLocalize(base.startupUnknownBody);

  @override
  String startupServer(String url) =>
      pseudoLocalize(base.startupServer(pseudoMarker(0)), <String>[url]);

  @override
  String startupDetail(String detail) =>
      pseudoLocalize(base.startupDetail(pseudoMarker(0)), <String>[detail]);

  @override
  String startupEnvironment(String name) =>
      pseudoLocalize(base.startupEnvironment(pseudoMarker(0)), <String>[name]);

  @override
  String get startupChangeServer => pseudoLocalize(base.startupChangeServer);

  @override
  String get envDevelopment => pseudoLocalize(base.envDevelopment);

  @override
  String get envStaging => pseudoLocalize(base.envStaging);

  @override
  String get envProduction => pseudoLocalize(base.envProduction);

  @override
  String get envBadgeDevelopment => pseudoLocalize(base.envBadgeDevelopment);

  @override
  String get envBadgeStaging => pseudoLocalize(base.envBadgeStaging);

  @override
  String envBadgeA11y(String name, String host) => pseudoLocalize(
    base.envBadgeA11y(pseudoMarker(0), pseudoMarker(1)),
    <String>[name, host],
  );

  @override
  String get serverTitle => pseudoLocalize(base.serverTitle);

  @override
  String get serverLabel => pseudoLocalize(base.serverLabel);

  @override
  String get serverHelp => pseudoLocalize(base.serverHelp);

  @override
  String serverDefault(String url) =>
      pseudoLocalize(base.serverDefault(pseudoMarker(0)), <String>[url]);

  @override
  String get serverSave => pseudoLocalize(base.serverSave);

  @override
  String get serverReset => pseudoLocalize(base.serverReset);

  @override
  String get serverInvalid => pseudoLocalize(base.serverInvalid);

  @override
  String get serverHttpsRequired => pseudoLocalize(base.serverHttpsRequired);

  @override
  String get serverWrongPath => pseudoLocalize(base.serverWrongPath);

  @override
  String get signInTitle => pseudoLocalize(base.signInTitle);

  @override
  String get signInSubtitle => pseudoLocalize(base.signInSubtitle);

  @override
  String get signInEmailLabel => pseudoLocalize(base.signInEmailLabel);

  @override
  String get signInEmailPlaceholder =>
      pseudoLocalize(base.signInEmailPlaceholder);

  @override
  String get signInPasswordLabel => pseudoLocalize(base.signInPasswordLabel);

  @override
  String get signInPasswordShow => pseudoLocalize(base.signInPasswordShow);

  @override
  String get signInPasswordHide => pseudoLocalize(base.signInPasswordHide);

  @override
  String get signInForgot => pseudoLocalize(base.signInForgot);

  @override
  String get signInSubmit => pseudoLocalize(base.signInSubmit);

  @override
  String get signInLoading => pseudoLocalize(base.signInLoading);

  @override
  String get signInNoAccess => pseudoLocalize(base.signInNoAccess);

  @override
  String get signInErrorRequired => pseudoLocalize(base.signInErrorRequired);

  @override
  String get signInErrorEmailFormat =>
      pseudoLocalize(base.signInErrorEmailFormat);

  @override
  String get signInErrorInvalid => pseudoLocalize(base.signInErrorInvalid);

  @override
  String get signInErrorNoPermission =>
      pseudoLocalize(base.signInErrorNoPermission);

  @override
  String signInErrorThrottled(String time) => pseudoLocalize(
    base.signInErrorThrottled(pseudoMarker(0)),
    <String>[time],
  );

  @override
  String signInRetryIn(String time) =>
      pseudoLocalize(base.signInRetryIn(pseudoMarker(0)), <String>[time]);

  @override
  String get signInAvailable => pseudoLocalize(base.signInAvailable);

  @override
  String get signInErrorServer => pseudoLocalize(base.signInErrorServer);

  @override
  String get signInOfflineBody => pseudoLocalize(base.signInOfflineBody);

  @override
  String get signInCodeTitle => pseudoLocalize(base.signInCodeTitle);

  @override
  String signInCodeBody(String email) =>
      pseudoLocalize(base.signInCodeBody(pseudoMarker(0)), <String>[email]);

  @override
  String get signInCodeLabel => pseudoLocalize(base.signInCodeLabel);

  @override
  String get signInCodeSubmit => pseudoLocalize(base.signInCodeSubmit);

  @override
  String get signInCodeResend => pseudoLocalize(base.signInCodeResend);

  @override
  String get signInCodeSent => pseudoLocalize(base.signInCodeSent);

  @override
  String get signInCodeWait => pseudoLocalize(base.signInCodeWait);

  @override
  String get signInCodeWrong => pseudoLocalize(base.signInCodeWrong);

  @override
  String get signInCodeExpired => pseudoLocalize(base.signInCodeExpired);

  @override
  String get signInCodeLocked => pseudoLocalize(base.signInCodeLocked);

  @override
  String get signInAppUpdated => pseudoLocalize(base.signInAppUpdated);

  @override
  String get biometricsTitleFaceId =>
      pseudoLocalize(base.biometricsTitleFaceId);

  @override
  String get biometricsTitleTouchId =>
      pseudoLocalize(base.biometricsTitleTouchId);

  @override
  String get biometricsTitleAndroid =>
      pseudoLocalize(base.biometricsTitleAndroid);

  @override
  String get biometricsBody => pseudoLocalize(base.biometricsBody);

  @override
  String get biometricsEnableFaceId =>
      pseudoLocalize(base.biometricsEnableFaceId);

  @override
  String get biometricsEnableTouchId =>
      pseudoLocalize(base.biometricsEnableTouchId);

  @override
  String get biometricsEnableAndroid =>
      pseudoLocalize(base.biometricsEnableAndroid);

  @override
  String get biometricsNotNow => pseudoLocalize(base.biometricsNotNow);

  @override
  String get biometricsReason => pseudoLocalize(base.biometricsReason);

  @override
  String biometricsPromptSubtitleAndroid(String restaurant) => pseudoLocalize(
    base.biometricsPromptSubtitleAndroid(pseudoMarker(0)),
    <String>[restaurant],
  );

  @override
  String get biometricsFailed => pseudoLocalize(base.biometricsFailed);

  @override
  String get biometricsNotEnrolledFaceId =>
      pseudoLocalize(base.biometricsNotEnrolledFaceId);

  @override
  String get biometricsNotEnrolledTouchId =>
      pseudoLocalize(base.biometricsNotEnrolledTouchId);

  @override
  String get biometricsNotEnrolledAndroid =>
      pseudoLocalize(base.biometricsNotEnrolledAndroid);

  @override
  String get unlockButtonFaceId => pseudoLocalize(base.unlockButtonFaceId);

  @override
  String get unlockButtonTouchId => pseudoLocalize(base.unlockButtonTouchId);

  @override
  String get unlockButtonAndroid => pseudoLocalize(base.unlockButtonAndroid);

  @override
  String get unlockUsePassword => pseudoLocalize(base.unlockUsePassword);

  @override
  String get unlockChanged => pseudoLocalize(base.unlockChanged);

  @override
  String get unlockLockedOut => pseudoLocalize(base.unlockLockedOut);

  @override
  String get topBarRecent => pseudoLocalize(base.topBarRecent);

  @override
  String topBarMenu(String name) =>
      pseudoLocalize(base.topBarMenu(pseudoMarker(0)), <String>[name]);

  @override
  String get readyTitle => pseudoLocalize(base.readyTitle);

  @override
  String get readyHint => pseudoLocalize(base.readyHint);

  @override
  String get readyScan => pseudoLocalize(base.readyScan);

  @override
  String get readyTapCard => pseudoLocalize(base.readyTapCard);

  @override
  String get readySell => pseudoLocalize(base.readySell);

  @override
  String get readyPendingTitle => pseudoLocalize(base.readyPendingTitle);

  @override
  String readyPendingBody(String amount, String last4) => pseudoLocalize(
    base.readyPendingBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[amount, last4],
  );

  @override
  String get readyDeliveryTitle => pseudoLocalize(base.readyDeliveryTitle);

  @override
  String readyDeliveryBody(String batch, String cards) => pseudoLocalize(
    base.readyDeliveryBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[batch, cards],
  );

  @override
  String readyDeliveryBodyMany(int count) =>
      pseudoLocalize(base.readyDeliveryBodyMany(count), <String>[]);

  @override
  String get readyDeliveryAction => pseudoLocalize(base.readyDeliveryAction);

  @override
  String readyPendingBooked(String amount) => pseudoLocalize(
    base.readyPendingBooked(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String readyPendingNotBooked(String amount) => pseudoLocalize(
    base.readyPendingNotBooked(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get readyOnline => pseudoLocalize(base.readyOnline);

  @override
  String get offlineTitle => pseudoLocalize(base.offlineTitle);

  @override
  String get offlineBody => pseudoLocalize(base.offlineBody);

  @override
  String get maintenanceDefault => pseudoLocalize(base.maintenanceDefault);

  @override
  String get maintenanceDismiss => pseudoLocalize(base.maintenanceDismiss);

  @override
  String get scanDetected => pseudoLocalize(base.scanDetected);

  @override
  String get scanLookingUp => pseudoLocalize(base.scanLookingUp);

  @override
  String get scanSlow => pseudoLocalize(base.scanSlow);

  @override
  String get cardTitle => pseudoLocalize(base.cardTitle);

  @override
  String get cardWaiting => pseudoLocalize(base.cardWaiting);

  @override
  String get cardChecking => pseudoLocalize(base.cardChecking);

  @override
  String get cardSlow => pseudoLocalize(base.cardSlow);

  @override
  String get cardDone => pseudoLocalize(base.cardDone);

  @override
  String get cardFailed => pseudoLocalize(base.cardFailed);

  @override
  String get balanceCardOverline => pseudoLocalize(base.balanceCardOverline);

  @override
  String balanceCardValidUntil(String date) => pseudoLocalize(
    base.balanceCardValidUntil(pseudoMarker(0)),
    <String>[date],
  );

  @override
  String get balanceCardNoExpiry => pseudoLocalize(base.balanceCardNoExpiry);

  @override
  String balanceCardMasked(String last4) =>
      pseudoLocalize(base.balanceCardMasked(pseudoMarker(0)), <String>[last4]);

  @override
  String balanceCardA11y(
    String restaurant,
    String spokenAmount,
    String last4,
  ) => pseudoLocalize(
    base.balanceCardA11y(pseudoMarker(0), pseudoMarker(1), pseudoMarker(2)),
    <String>[restaurant, spokenAmount, last4],
  );

  @override
  String chargeVoucherNumberA11y(String number) => pseudoLocalize(
    base.chargeVoucherNumberA11y(pseudoMarker(0)),
    <String>[number],
  );

  @override
  String get a11yChargeClose => pseudoLocalize(base.a11yChargeClose);

  @override
  String a11yAmount(String spokenAmount) =>
      pseudoLocalize(base.a11yAmount(pseudoMarker(0)), <String>[spokenAmount]);

  @override
  String get chargeEnterAmount => pseudoLocalize(base.chargeEnterAmount);

  @override
  String chargeRedeem(String amount) =>
      pseudoLocalize(base.chargeRedeem(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeRedeemFull(String amount) =>
      pseudoLocalize(base.chargeRedeemFull(pseudoMarker(0)), <String>[amount]);

  @override
  String get chargeHold => pseudoLocalize(base.chargeHold);

  @override
  String get a11yHoldHint => pseudoLocalize(base.a11yHoldHint);

  @override
  String chargeRedeeming(String amount) =>
      pseudoLocalize(base.chargeRedeeming(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeOverBalance(String diff) =>
      pseudoLocalize(base.chargeOverBalance(pseudoMarker(0)), <String>[diff]);

  @override
  String a11yOverBalance(String diff) =>
      pseudoLocalize(base.a11yOverBalance(pseudoMarker(0)), <String>[diff]);

  @override
  String chargeUseBalance(String amount) =>
      pseudoLocalize(base.chargeUseBalance(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeUseMax(String amount) =>
      pseudoLocalize(base.chargeUseMax(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeMaxSingle(String amount) =>
      pseudoLocalize(base.chargeMaxSingle(pseudoMarker(0)), <String>[amount]);

  @override
  String get chargeFullOnly => pseudoLocalize(base.chargeFullOnly);

  @override
  String get chargeVelocityTitle => pseudoLocalize(base.chargeVelocityTitle);

  @override
  String chargeVelocityBodyTime(int minutes) =>
      pseudoLocalize(base.chargeVelocityBodyTime(minutes), <String>[]);

  @override
  String chargeRateLimited(int seconds) =>
      pseudoLocalize(base.chargeRateLimited(seconds), <String>[]);

  @override
  String chargeDailyLimit(String amount) =>
      pseudoLocalize(base.chargeDailyLimit(pseudoMarker(0)), <String>[amount]);

  @override
  String get chargePresentmentExpired =>
      pseudoLocalize(base.chargePresentmentExpired);

  @override
  String get chargePendingTitle => pseudoLocalize(base.chargePendingTitle);

  @override
  String chargePendingBody(String amount) =>
      pseudoLocalize(base.chargePendingBody(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeEarlierBooked(String amount) => pseudoLocalize(
    base.chargeEarlierBooked(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get keypadDoubleZero => pseudoLocalize(base.keypadDoubleZero);

  @override
  String get keypadDelete => pseudoLocalize(base.keypadDelete);

  @override
  String get keypadDeleteHint => pseudoLocalize(base.keypadDeleteHint);

  @override
  String get keypadCleared => pseudoLocalize(base.keypadCleared);

  @override
  String get keypadMaxReached => pseudoLocalize(base.keypadMaxReached);

  @override
  String get badgeActive => pseudoLocalize(base.badgeActive);

  @override
  String get badgeUsedUp => pseudoLocalize(base.badgeUsedUp);

  @override
  String get badgeBlocked => pseudoLocalize(base.badgeBlocked);

  @override
  String get badgeExpired => pseudoLocalize(base.badgeExpired);

  @override
  String get voucherBlocked => pseudoLocalize(base.voucherBlocked);

  @override
  String voucherBlockedReason(String reason) => pseudoLocalize(
    base.voucherBlockedReason(pseudoMarker(0)),
    <String>[reason],
  );

  @override
  String get voucherExpired => pseudoLocalize(base.voucherExpired);

  @override
  String voucherExpiredBody(String date) =>
      pseudoLocalize(base.voucherExpiredBody(pseudoMarker(0)), <String>[date]);

  @override
  String get voucherEmpty => pseudoLocalize(base.voucherEmpty);

  @override
  String get voucherEmptyBody => pseudoLocalize(base.voucherEmptyBody);

  @override
  String get redeemSlow => pseudoLocalize(base.redeemSlow);

  @override
  String get uncertainTitle => pseudoLocalize(base.uncertainTitle);

  @override
  String get uncertainBody => pseudoLocalize(base.uncertainBody);

  @override
  String uncertainRetrying(int n) =>
      pseudoLocalize(base.uncertainRetrying(n), <String>[]);

  @override
  String get uncertainGuestHint => pseudoLocalize(base.uncertainGuestHint);

  @override
  String get uncertainFailedBody => pseudoLocalize(base.uncertainFailedBody);

  @override
  String get uncertainCancelled => pseudoLocalize(base.uncertainCancelled);

  @override
  String get uncertainCancelledGuestHint =>
      pseudoLocalize(base.uncertainCancelledGuestHint);

  @override
  String redeemBalanceChanged(String amount) => pseudoLocalize(
    base.redeemBalanceChanged(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get successTitle => pseudoLocalize(base.successTitle);

  @override
  String successRemaining(String amount) =>
      pseudoLocalize(base.successRemaining(pseudoMarker(0)), <String>[amount]);

  @override
  String get successEmpty => pseudoLocalize(base.successEmpty);

  @override
  String get successNext => pseudoLocalize(base.successNext);

  @override
  String get successNextCard => pseudoLocalize(base.successNextCard);

  @override
  String get successShowGuest => pseudoLocalize(base.successShowGuest);

  @override
  String successCard(String last4) =>
      pseudoLocalize(base.successCard(pseudoMarker(0)), <String>[last4]);

  @override
  String get guestRemainingLabel => pseudoLocalize(base.guestRemainingLabel);

  @override
  String a11ySuccess(String amount, String balance) => pseudoLocalize(
    base.a11ySuccess(pseudoMarker(0), pseudoMarker(1)),
    <String>[amount, balance],
  );

  @override
  String get problemNotRecognizedTitle =>
      pseudoLocalize(base.problemNotRecognizedTitle);

  @override
  String get problemNotRecognizedBody =>
      pseudoLocalize(base.problemNotRecognizedBody);

  @override
  String get problemCardOnlyTitle => pseudoLocalize(base.problemCardOnlyTitle);

  @override
  String get problemCardOnlyBody => pseudoLocalize(base.problemCardOnlyBody);

  @override
  String get problemCardNotRecognizedTitle =>
      pseudoLocalize(base.problemCardNotRecognizedTitle);

  @override
  String get problemCardNotRecognizedBody =>
      pseudoLocalize(base.problemCardNotRecognizedBody);

  @override
  String get problemCardUnverifiedTitle =>
      pseudoLocalize(base.problemCardUnverifiedTitle);

  @override
  String get problemCardUnverifiedBody =>
      pseudoLocalize(base.problemCardUnverifiedBody);

  @override
  String get problemCardNotUsableTitle =>
      pseudoLocalize(base.problemCardNotUsableTitle);

  @override
  String get problemCardNotUsableNotActive =>
      pseudoLocalize(base.problemCardNotUsableNotActive);

  @override
  String get problemCardNotUsableSuspended =>
      pseudoLocalize(base.problemCardNotUsableSuspended);

  @override
  String get problemCardNotUsableInvalid =>
      pseudoLocalize(base.problemCardNotUsableInvalid);

  @override
  String get problemCardNotUsableOtherRestaurant =>
      pseudoLocalize(base.problemCardNotUsableOtherRestaurant);

  @override
  String get problemCardMovedTitle =>
      pseudoLocalize(base.problemCardMovedTitle);

  @override
  String get problemCardMovedBody => pseudoLocalize(base.problemCardMovedBody);

  @override
  String get problemNfcOffTitle => pseudoLocalize(base.problemNfcOffTitle);

  @override
  String get problemNfcOffBody => pseudoLocalize(base.problemNfcOffBody);

  @override
  String get problemNfcUnsupportedTitle =>
      pseudoLocalize(base.problemNfcUnsupportedTitle);

  @override
  String get problemNfcUnsupportedBody =>
      pseudoLocalize(base.problemNfcUnsupportedBody);

  @override
  String get problemThrottledTitle =>
      pseudoLocalize(base.problemThrottledTitle);

  @override
  String get problemThrottledBody => pseudoLocalize(base.problemThrottledBody);

  @override
  String problemScanAgainIn(String time) =>
      pseudoLocalize(base.problemScanAgainIn(pseudoMarker(0)), <String>[time]);

  @override
  String get problemNetworkBody => pseudoLocalize(base.problemNetworkBody);

  @override
  String get problemServerTitle => pseudoLocalize(base.problemServerTitle);

  @override
  String get problemServerBody => pseudoLocalize(base.problemServerBody);

  @override
  String get saleTitle => pseudoLocalize(base.saleTitle);

  @override
  String get saleAmountLabel => pseudoLocalize(base.saleAmountLabel);

  @override
  String saleAmountRange(String min, String max) => pseudoLocalize(
    base.saleAmountRange(pseudoMarker(0), pseudoMarker(1)),
    <String>[min, max],
  );

  @override
  String saleContinue(String amount) =>
      pseudoLocalize(base.saleContinue(pseudoMarker(0)), <String>[amount]);

  @override
  String get salePaymentLabel => pseudoLocalize(base.salePaymentLabel);

  @override
  String get salePaymentCash => pseudoLocalize(base.salePaymentCash);

  @override
  String get salePaymentCardTerminal =>
      pseudoLocalize(base.salePaymentCardTerminal);

  @override
  String get salePaymentBankTransfer =>
      pseudoLocalize(base.salePaymentBankTransfer);

  @override
  String get salePaymentComplimentary =>
      pseudoLocalize(base.salePaymentComplimentary);

  @override
  String get saleReferenceLabel => pseudoLocalize(base.saleReferenceLabel);

  @override
  String get saleReferenceRequired =>
      pseudoLocalize(base.saleReferenceRequired);

  @override
  String get saleReasonLabel => pseudoLocalize(base.saleReasonLabel);

  @override
  String get saleReasonRequired => pseudoLocalize(base.saleReasonRequired);

  @override
  String get saleEmailLabel => pseudoLocalize(base.saleEmailLabel);

  @override
  String get saleEmailHelperPdf => pseudoLocalize(base.saleEmailHelperPdf);

  @override
  String get saleEmailHelperNoMail =>
      pseudoLocalize(base.saleEmailHelperNoMail);

  @override
  String get saleEmailInvalid => pseudoLocalize(base.saleEmailInvalid);

  @override
  String get saleRecipientLabel => pseudoLocalize(base.saleRecipientLabel);

  @override
  String get saleMessageLabel => pseudoLocalize(base.saleMessageLabel);

  @override
  String get saleMessageHelper => pseudoLocalize(base.saleMessageHelper);

  @override
  String saleSubmit(String amount) =>
      pseudoLocalize(base.saleSubmit(pseudoMarker(0)), <String>[amount]);

  @override
  String get saleSubmitting => pseudoLocalize(base.saleSubmitting);

  @override
  String get saleFailedTitle => pseudoLocalize(base.saleFailedTitle);

  @override
  String get saleFailedBody => pseudoLocalize(base.saleFailedBody);

  @override
  String get saleUncertainTitle => pseudoLocalize(base.saleUncertainTitle);

  @override
  String get saleUncertainBody => pseudoLocalize(base.saleUncertainBody);

  @override
  String get saleNotAllowedTitle => pseudoLocalize(base.saleNotAllowedTitle);

  @override
  String get saleNotAllowedBody => pseudoLocalize(base.saleNotAllowedBody);

  @override
  String get saleDoneTitle => pseudoLocalize(base.saleDoneTitle);

  @override
  String saleDoneValue(String amount) =>
      pseudoLocalize(base.saleDoneValue(pseudoMarker(0)), <String>[amount]);

  @override
  String get saleDoneBody => pseudoLocalize(base.saleDoneBody);

  @override
  String get salePrint => pseudoLocalize(base.salePrint);

  @override
  String get salePrinted => pseudoLocalize(base.salePrinted);

  @override
  String get salePrintFailed => pseudoLocalize(base.salePrintFailed);

  @override
  String get saleAnother => pseudoLocalize(base.saleAnother);

  @override
  String get saleLeaveTitle => pseudoLocalize(base.saleLeaveTitle);

  @override
  String get saleLeaveBody => pseudoLocalize(base.saleLeaveBody);

  @override
  String get saleLeaveConfirm => pseudoLocalize(base.saleLeaveConfirm);

  @override
  String get saleLeaveUncertainTitle =>
      pseudoLocalize(base.saleLeaveUncertainTitle);

  @override
  String get saleLeaveUncertainBody =>
      pseudoLocalize(base.saleLeaveUncertainBody);

  @override
  String get saleNoQrTitle => pseudoLocalize(base.saleNoQrTitle);

  @override
  String get saleNoQrBody => pseudoLocalize(base.saleNoQrBody);

  @override
  String get saleQrA11y => pseudoLocalize(base.saleQrA11y);

  @override
  String get saleCardDoneTitle => pseudoLocalize(base.saleCardDoneTitle);

  @override
  String get saleCardFailedTitle => pseudoLocalize(base.saleCardFailedTitle);

  @override
  String get saleCardNotUsable => pseudoLocalize(base.saleCardNotUsable);

  @override
  String get reloadReady => pseudoLocalize(base.reloadReady);

  @override
  String get reloadTitle => pseudoLocalize(base.reloadTitle);

  @override
  String get reloadTap => pseudoLocalize(base.reloadTap);

  @override
  String get reloadTapAgain => pseudoLocalize(base.reloadTapAgain);

  @override
  String get reloadAmountLabel => pseudoLocalize(base.reloadAmountLabel);

  @override
  String reloadAmountMax(String max) =>
      pseudoLocalize(base.reloadAmountMax(pseudoMarker(0)), <String>[max]);

  @override
  String reloadSubmit(String amount) =>
      pseudoLocalize(base.reloadSubmit(pseudoMarker(0)), <String>[amount]);

  @override
  String get reloadSubmitting => pseudoLocalize(base.reloadSubmitting);

  @override
  String get reloadDoneTitle => pseudoLocalize(base.reloadDoneTitle);

  @override
  String reloadDoneBody(String amount, String balance) => pseudoLocalize(
    base.reloadDoneBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[amount, balance],
  );

  @override
  String get reloadAnother => pseudoLocalize(base.reloadAnother);

  @override
  String get reloadFailedTitle => pseudoLocalize(base.reloadFailedTitle);

  @override
  String get reloadFailedBody => pseudoLocalize(base.reloadFailedBody);

  @override
  String get reloadUncertainTitle => pseudoLocalize(base.reloadUncertainTitle);

  @override
  String get reloadUncertainBody => pseudoLocalize(base.reloadUncertainBody);

  @override
  String get reloadNotAllowedTitle =>
      pseudoLocalize(base.reloadNotAllowedTitle);

  @override
  String get reloadNotAllowedBody => pseudoLocalize(base.reloadNotAllowedBody);

  @override
  String get reloadOffTitle => pseudoLocalize(base.reloadOffTitle);

  @override
  String get reloadOffBody => pseudoLocalize(base.reloadOffBody);

  @override
  String get reloadVoucherBlockedTitle =>
      pseudoLocalize(base.reloadVoucherBlockedTitle);

  @override
  String get reloadVoucherBlockedBody =>
      pseudoLocalize(base.reloadVoucherBlockedBody);

  @override
  String get reloadVoucherExpiredTitle =>
      pseudoLocalize(base.reloadVoucherExpiredTitle);

  @override
  String get reloadVoucherExpiredBody =>
      pseudoLocalize(base.reloadVoucherExpiredBody);

  @override
  String get loyaltyNotAllowedTitle =>
      pseudoLocalize(base.loyaltyNotAllowedTitle);

  @override
  String get loyaltyNotAllowedBody =>
      pseudoLocalize(base.loyaltyNotAllowedBody);

  @override
  String get loyaltyVoucherOnlyBody =>
      pseudoLocalize(base.loyaltyVoucherOnlyBody);

  @override
  String get reloadLoyaltyNote => pseudoLocalize(base.reloadLoyaltyNote);

  @override
  String get reloadLoyaltyOnlyTitle =>
      pseudoLocalize(base.reloadLoyaltyOnlyTitle);

  @override
  String get reloadLoyaltyOnlyBody =>
      pseudoLocalize(base.reloadLoyaltyOnlyBody);

  @override
  String get reloadCardReplaced => pseudoLocalize(base.reloadCardReplaced);

  @override
  String get reloadCardRevoked => pseudoLocalize(base.reloadCardRevoked);

  @override
  String get reloadCardLost => pseudoLocalize(base.reloadCardLost);

  @override
  String get reloadCardNotInStock => pseudoLocalize(base.reloadCardNotInStock);

  @override
  String get reloadCardOtherCard => pseudoLocalize(base.reloadCardOtherCard);

  @override
  String get reloadNewCardTitle => pseudoLocalize(base.reloadNewCardTitle);

  @override
  String reloadNewCardBody(String number) =>
      pseudoLocalize(base.reloadNewCardBody(pseudoMarker(0)), <String>[number]);

  @override
  String reloadNewCardDoneBody(String number, String balance) => pseudoLocalize(
    base.reloadNewCardDoneBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[number, balance],
  );

  @override
  String get reloadNewCardNotAllowedBody =>
      pseudoLocalize(base.reloadNewCardNotAllowedBody);

  @override
  String get reloadLeaveUncertainTitle =>
      pseudoLocalize(base.reloadLeaveUncertainTitle);

  @override
  String get reloadLeaveUncertainBody =>
      pseudoLocalize(base.reloadLeaveUncertainBody);

  @override
  String get qrTitle => pseudoLocalize(base.qrTitle);

  @override
  String get qrHint => pseudoLocalize(base.qrHint);

  @override
  String get qrNotVoucher => pseudoLocalize(base.qrNotVoucher);

  @override
  String get qrDark => pseudoLocalize(base.qrDark);

  @override
  String get qrTorchOn => pseudoLocalize(base.qrTorchOn);

  @override
  String get qrTorchOff => pseudoLocalize(base.qrTorchOff);

  @override
  String get recentTitle => pseudoLocalize(base.recentTitle);

  @override
  String recentSummary(int count, String amount) => pseudoLocalize(
    base.recentSummary(count, pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String recentRowRemaining(String amount) => pseudoLocalize(
    base.recentRowRemaining(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get recentRowEmpty => pseudoLocalize(base.recentRowEmpty);

  @override
  String recentRowA11y(
    String time,
    String last4,
    String amount,
    String balance,
  ) => pseudoLocalize(
    base.recentRowA11y(
      pseudoMarker(0),
      pseudoMarker(1),
      pseudoMarker(2),
      pseudoMarker(3),
    ),
    <String>[time, last4, amount, balance],
  );

  @override
  String get recentEmptyTitle => pseudoLocalize(base.recentEmptyTitle);

  @override
  String get recentEmptyBody => pseudoLocalize(base.recentEmptyBody);

  @override
  String get recentFooter => pseudoLocalize(base.recentFooter);

  @override
  String get recentLimit => pseudoLocalize(base.recentLimit);

  @override
  String get recentDetailTitle => pseudoLocalize(base.recentDetailTitle);

  @override
  String get recentDetailTime => pseudoLocalize(base.recentDetailTime);

  @override
  String get recentDetailVoucher => pseudoLocalize(base.recentDetailVoucher);

  @override
  String get recentDetailAmount => pseudoLocalize(base.recentDetailAmount);

  @override
  String get recentDetailRemaining =>
      pseudoLocalize(base.recentDetailRemaining);

  @override
  String get recentDetailTransaction =>
      pseudoLocalize(base.recentDetailTransaction);

  @override
  String get recentDetailSupportCode =>
      pseudoLocalize(base.recentDetailSupportCode);

  @override
  String get recentDetailReverseHint =>
      pseudoLocalize(base.recentDetailReverseHint);

  @override
  String get menuClose => pseudoLocalize(base.menuClose);

  @override
  String get menuAccount => pseudoLocalize(base.menuAccount);

  @override
  String get menuRestaurant => pseudoLocalize(base.menuRestaurant);

  @override
  String get menuDevice => pseudoLocalize(base.menuDevice);

  @override
  String get menuSectionSettings => pseudoLocalize(base.menuSectionSettings);

  @override
  String get menuLanguage => pseudoLocalize(base.menuLanguage);

  @override
  String get menuLanguageFailed => pseudoLocalize(base.menuLanguageFailed);

  @override
  String get menuTheme => pseudoLocalize(base.menuTheme);

  @override
  String get menuThemeSystem => pseudoLocalize(base.menuThemeSystem);

  @override
  String get menuThemeLight => pseudoLocalize(base.menuThemeLight);

  @override
  String get menuThemeDark => pseudoLocalize(base.menuThemeDark);

  @override
  String get menuSunlightTip => pseudoLocalize(base.menuSunlightTip);

  @override
  String get menuSound => pseudoLocalize(base.menuSound);

  @override
  String get menuHaptics => pseudoLocalize(base.menuHaptics);

  @override
  String get menuHapticsUnavailable =>
      pseudoLocalize(base.menuHapticsUnavailable);

  @override
  String get menuKeepScreenOn => pseudoLocalize(base.menuKeepScreenOn);

  @override
  String get menuKeepScreenOnCaption =>
      pseudoLocalize(base.menuKeepScreenOnCaption);

  @override
  String get menuHelp => pseudoLocalize(base.menuHelp);

  @override
  String menuVersion(String version) =>
      pseudoLocalize(base.menuVersion(pseudoMarker(0)), <String>[version]);

  @override
  String get menuSignOut => pseudoLocalize(base.menuSignOut);

  @override
  String get menuSignOutConfirmTitle =>
      pseudoLocalize(base.menuSignOutConfirmTitle);

  @override
  String get menuSignOutConfirmBody =>
      pseudoLocalize(base.menuSignOutConfirmBody);

  @override
  String get menuSignOutConfirmAction =>
      pseudoLocalize(base.menuSignOutConfirmAction);

  @override
  String get menuCards => pseudoLocalize(base.menuCards);

  @override
  String get menuCardsReceive => pseudoLocalize(base.menuCardsReceive);

  @override
  String get menuCardsFind => pseudoLocalize(base.menuCardsFind);

  @override
  String get menuCardsOrder => pseudoLocalize(base.menuCardsOrder);

  @override
  String get menuCardsPickup => pseudoLocalize(base.menuCardsPickup);

  @override
  String get cardsReceiveNone => pseudoLocalize(base.cardsReceiveNone);

  @override
  String cardsReceiveBatch(int count) =>
      pseudoLocalize(base.cardsReceiveBatch(count), <String>[]);

  @override
  String get cardsReceiveOnHold => pseudoLocalize(base.cardsReceiveOnHold);

  @override
  String get cardsReceiveCount => pseudoLocalize(base.cardsReceiveCount);

  @override
  String cardsReceiveContinue(int count) =>
      pseudoLocalize(base.cardsReceiveContinue(count), <String>[]);

  @override
  String get cardsReceiveTap => pseudoLocalize(base.cardsReceiveTap);

  @override
  String get cardsReceiveDone => pseudoLocalize(base.cardsReceiveDone);

  @override
  String get cardsReceiveHold => pseudoLocalize(base.cardsReceiveHold);

  @override
  String get cardsReceiveWrongCard =>
      pseudoLocalize(base.cardsReceiveWrongCard);

  @override
  String get cardsOrderCount => pseudoLocalize(base.cardsOrderCount);

  @override
  String get cardsOrderHint => pseudoLocalize(base.cardsOrderHint);

  @override
  String cardsOrderSubmit(int count) =>
      pseudoLocalize(base.cardsOrderSubmit(count), <String>[]);

  @override
  String get cardsOrderDone => pseudoLocalize(base.cardsOrderDone);

  @override
  String cardsOrderOpen(int count) =>
      pseudoLocalize(base.cardsOrderOpen(count), <String>[]);

  @override
  String cardsOrderDeclined(String reason) => pseudoLocalize(
    base.cardsOrderDeclined(pseudoMarker(0)),
    <String>[reason],
  );

  @override
  String get cardsOrderTooMany => pseudoLocalize(base.cardsOrderTooMany);

  @override
  String get cardsFindLabel => pseudoLocalize(base.cardsFindLabel);

  @override
  String get cardsFindHelper => pseudoLocalize(base.cardsFindHelper);

  @override
  String get cardsFindAction => pseudoLocalize(base.cardsFindAction);

  @override
  String get cardsFindNotFound => pseudoLocalize(base.cardsFindNotFound);

  @override
  String get cardsStateActive => pseudoLocalize(base.cardsStateActive);

  @override
  String get cardsStateSuspended => pseudoLocalize(base.cardsStateSuspended);

  @override
  String get cardsStateReplaced => pseudoLocalize(base.cardsStateReplaced);

  @override
  String get cardsStateAvailable => pseudoLocalize(base.cardsStateAvailable);

  @override
  String get cardsStateOther => pseudoLocalize(base.cardsStateOther);

  @override
  String cardsBalance(String amount) =>
      pseudoLocalize(base.cardsBalance(pseudoMarker(0)), <String>[amount]);

  @override
  String get cardsSuspend => pseudoLocalize(base.cardsSuspend);

  @override
  String get cardsResume => pseudoLocalize(base.cardsResume);

  @override
  String get cardsReplace => pseudoLocalize(base.cardsReplace);

  @override
  String get cardsReasonTitle => pseudoLocalize(base.cardsReasonTitle);

  @override
  String get cardsReasonLost => pseudoLocalize(base.cardsReasonLost);

  @override
  String get cardsReasonStolen => pseudoLocalize(base.cardsReasonStolen);

  @override
  String get cardsReasonDamaged => pseudoLocalize(base.cardsReasonDamaged);

  @override
  String get cardsReasonFound => pseudoLocalize(base.cardsReasonFound);

  @override
  String get cardsReplaceTap => pseudoLocalize(base.cardsReplaceTap);

  @override
  String get cardsReplaceTapOld => pseudoLocalize(base.cardsReplaceTapOld);

  @override
  String get cardsReplaceOwnerOnly =>
      pseudoLocalize(base.cardsReplaceOwnerOnly);

  @override
  String cardsReplaceDone(String number) =>
      pseudoLocalize(base.cardsReplaceDone(pseudoMarker(0)), <String>[number]);

  @override
  String get cardsSuspendDone => pseudoLocalize(base.cardsSuspendDone);

  @override
  String get cardsResumeDone => pseudoLocalize(base.cardsResumeDone);

  @override
  String get cardsResumeTap => pseudoLocalize(base.cardsResumeTap);

  @override
  String get cardsResumeCompromised =>
      pseudoLocalize(base.cardsResumeCompromised);

  @override
  String get cardsVoucherBlocked => pseudoLocalize(base.cardsVoucherBlocked);

  @override
  String get cardsVoucherExpired => pseudoLocalize(base.cardsVoucherExpired);

  @override
  String get cardsVoucherClosed => pseudoLocalize(base.cardsVoucherClosed);

  @override
  String get cardsErrorState => pseudoLocalize(base.cardsErrorState);

  @override
  String get cardsErrorOtherCard => pseudoLocalize(base.cardsErrorOtherCard);

  @override
  String get cardsErrorForbidden => pseudoLocalize(base.cardsErrorForbidden);

  @override
  String get cardsErrorNotLinked => pseudoLocalize(base.cardsErrorNotLinked);

  @override
  String get cardsErrorUncertain => pseudoLocalize(base.cardsErrorUncertain);

  @override
  String get pickupScan => pseudoLocalize(base.pickupScan);

  @override
  String get pickupScanAction => pseudoLocalize(base.pickupScanAction);

  @override
  String get pickupScanTitle => pseudoLocalize(base.pickupScanTitle);

  @override
  String pickupVoucher(String balance) =>
      pseudoLocalize(base.pickupVoucher(pseudoMarker(0)), <String>[balance]);

  @override
  String get pickupTap => pseudoLocalize(base.pickupTap);

  @override
  String get pickupTapAction => pseudoLocalize(base.pickupTapAction);

  @override
  String get pickupDoneTitle => pseudoLocalize(base.pickupDoneTitle);

  @override
  String pickupDoneBody(String number, String balance) => pseudoLocalize(
    base.pickupDoneBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[number, balance],
  );

  @override
  String get pickupNext => pseudoLocalize(base.pickupNext);

  @override
  String get pickupErrorNotRecognized =>
      pseudoLocalize(base.pickupErrorNotRecognized);

  @override
  String get pickupErrorNotOnline => pseudoLocalize(base.pickupErrorNotOnline);

  @override
  String get pickupErrorNoCard => pseudoLocalize(base.pickupErrorNoCard);

  @override
  String get pickupErrorPickedUp => pseudoLocalize(base.pickupErrorPickedUp);

  @override
  String pickupErrorTooEarly(String date) =>
      pseudoLocalize(base.pickupErrorTooEarly(pseudoMarker(0)), <String>[date]);

  @override
  String get pickupErrorScanAgain => pseudoLocalize(base.pickupErrorScanAgain);

  @override
  String get pickupErrorNotUsable => pseudoLocalize(base.pickupErrorNotUsable);

  @override
  String get cardsFailed => pseudoLocalize(base.cardsFailed);

  @override
  String get sessionExpired => pseudoLocalize(base.sessionExpired);

  @override
  String get sessionExpiredBody => pseudoLocalize(base.sessionExpiredBody);

  @override
  String get sessionExpiredAction => pseudoLocalize(base.sessionExpiredAction);

  @override
  String get forbiddenTitle => pseudoLocalize(base.forbiddenTitle);

  @override
  String get forbiddenBody => pseudoLocalize(base.forbiddenBody);

  @override
  String get deviceRevokedTitle => pseudoLocalize(base.deviceRevokedTitle);

  @override
  String get deviceRevokedBody => pseudoLocalize(base.deviceRevokedBody);

  @override
  String get deviceRevokedAction => pseudoLocalize(base.deviceRevokedAction);

  @override
  String get suspendedTitle => pseudoLocalize(base.suspendedTitle);

  @override
  String get suspendedBody => pseudoLocalize(base.suspendedBody);

  @override
  String get deactivatedTitle => pseudoLocalize(base.deactivatedTitle);

  @override
  String get deactivatedBody => pseudoLocalize(base.deactivatedBody);

  @override
  String get updateTitle => pseudoLocalize(base.updateTitle);

  @override
  String get updateBody => pseudoLocalize(base.updateBody);

  @override
  String get updateAction => pseudoLocalize(base.updateAction);

  @override
  String get cameraDeniedTitle => pseudoLocalize(base.cameraDeniedTitle);

  @override
  String get cameraDeniedBody => pseudoLocalize(base.cameraDeniedBody);

  @override
  String get cameraDeniedAction => pseudoLocalize(base.cameraDeniedAction);

  @override
  String get cameraRestrictedBody => pseudoLocalize(base.cameraRestrictedBody);

  @override
  String get cameraUnavailableTitle =>
      pseudoLocalize(base.cameraUnavailableTitle);

  @override
  String get cameraUnavailableBody =>
      pseudoLocalize(base.cameraUnavailableBody);

  @override
  String get introSkip => pseudoLocalize(base.introSkip);

  @override
  String get introNext => pseudoLocalize(base.introNext);

  @override
  String get introStart => pseudoLocalize(base.introStart);

  @override
  String introPage(int n) => pseudoLocalize(base.introPage(n), <String>[]);

  @override
  String get intro1Title => pseudoLocalize(base.intro1Title);

  @override
  String get intro1Body => pseudoLocalize(base.intro1Body);

  @override
  String get intro2Title => pseudoLocalize(base.intro2Title);

  @override
  String intro2Body(String threshold) =>
      pseudoLocalize(base.intro2Body(pseudoMarker(0)), <String>[threshold]);

  @override
  String get intro3Title => pseudoLocalize(base.intro3Title);

  @override
  String get intro3Body => pseudoLocalize(base.intro3Body);

  @override
  String get stationTitle => pseudoLocalize(base.stationTitle);

  @override
  String get stationChoose => pseudoLocalize(base.stationChoose);

  @override
  String get stationEmpty => pseudoLocalize(base.stationEmpty);

  @override
  String get stationChooseHint => pseudoLocalize(base.stationChooseHint);

  @override
  String stationProgress(String done, String total) => pseudoLocalize(
    base.stationProgress(pseudoMarker(0), pseudoMarker(1)),
    <String>[done, total],
  );

  @override
  String get stationNoCard => pseudoLocalize(base.stationNoCard);

  @override
  String get stationCompleteTitle => pseudoLocalize(base.stationCompleteTitle);

  @override
  String stationCompleteBody(String total) => pseudoLocalize(
    base.stationCompleteBody(pseudoMarker(0)),
    <String>[total],
  );

  @override
  String get stationWaiting => pseudoLocalize(base.stationWaiting);

  @override
  String get stationWorking => pseudoLocalize(base.stationWorking);

  @override
  String stationDone(String number) =>
      pseudoLocalize(base.stationDone(pseudoMarker(0)), <String>[number]);

  @override
  String get stationFailed => pseudoLocalize(base.stationFailed);

  @override
  String get stationRejected => pseudoLocalize(base.stationRejected);

  @override
  String get stationUnknownChip => pseudoLocalize(base.stationUnknownChip);

  @override
  String get stationBatchClosed => pseudoLocalize(base.stationBatchClosed);

  @override
  String get stationFinish => pseudoLocalize(base.stationFinish);

  @override
  String a11ySpokenAmount(int euros, String cents) => pseudoLocalize(
    base.a11ySpokenAmount(euros, pseudoMarker(0)),
    <String>[cents],
  );

  @override
  String a11yVoucherLoaded(String restaurant, String spokenAmount) =>
      pseudoLocalize(
        base.a11yVoucherLoaded(pseudoMarker(0), pseudoMarker(1)),
        <String>[restaurant, spokenAmount],
      );

  @override
  String a11yProblem(String title, String body) => pseudoLocalize(
    base.a11yProblem(pseudoMarker(0), pseudoMarker(1)),
    <String>[title, body],
  );

  @override
  String get a11yReady => pseudoLocalize(base.a11yReady);

  @override
  String get a11yScanAvailable => pseudoLocalize(base.a11yScanAvailable);

  @override
  String get a11yRedeemAvailable => pseudoLocalize(base.a11yRedeemAvailable);
}
