// GENERATED by tool/import_strings.dart — do not edit.
// Pseudo-localisation wrapper for AppLocalizations (09 §6.5).

import '../../l10n/app_localizations.dart';
import 'pseudo_transform.dart';

/// [AppLocalizations] whose every message is pseudo-localised
/// with [pseudoLocalize]; placeholder values are kept intact.
class PseudoAppLocalizations extends AppLocalizations {
  /// Wraps [base].
  PseudoAppLocalizations(this.base) : super(base.localeName);

  /// The real localizations being transformed.
  final AppLocalizations base;

  @override
  String get appName => pseudoLocalize(base.appName);

  @override
  String get commonCancel => pseudoLocalize(base.commonCancel);

  @override
  String get commonClose => pseudoLocalize(base.commonClose);

  @override
  String get commonBack => pseudoLocalize(base.commonBack);

  @override
  String get commonDone => pseudoLocalize(base.commonDone);

  @override
  String get commonTryAgain => pseudoLocalize(base.commonTryAgain);

  @override
  String get commonScanAgain => pseudoLocalize(base.commonScanAgain);

  @override
  String get commonEnterNumber => pseudoLocalize(base.commonEnterNumber);

  @override
  String get commonEditNumber => pseudoLocalize(base.commonEditNumber);

  @override
  String get commonOpenSettings => pseudoLocalize(base.commonOpenSettings);

  @override
  String get commonBackToSignIn => pseudoLocalize(base.commonBackToSignIn);

  @override
  String get commonCheckAgain => pseudoLocalize(base.commonCheckAgain);

  @override
  String commonSupportCode(String code) =>
      pseudoLocalize(base.commonSupportCode(pseudoMarker(0)), <String>[code]);

  @override
  String commonSupportCodeA11y(String code) => pseudoLocalize(
    base.commonSupportCodeA11y(pseudoMarker(0)),
    <String>[code],
  );

  @override
  String get commonCopied => pseudoLocalize(base.commonCopied);

  @override
  String get redeemNothingBooked => pseudoLocalize(base.redeemNothingBooked);

  @override
  String get getManager => pseudoLocalize(base.getManager);

  @override
  String get splashLoading => pseudoLocalize(base.splashLoading);

  @override
  String get startupOfflineTitle => pseudoLocalize(base.startupOfflineTitle);

  @override
  String get startupOfflineBody => pseudoLocalize(base.startupOfflineBody);

  @override
  String get startupHostNotFoundTitle =>
      pseudoLocalize(base.startupHostNotFoundTitle);

  @override
  String startupHostNotFoundBody(String host) => pseudoLocalize(
    base.startupHostNotFoundBody(pseudoMarker(0)),
    <String>[host],
  );

  @override
  String get startupRefusedTitle => pseudoLocalize(base.startupRefusedTitle);

  @override
  String startupRefusedBody(String host) =>
      pseudoLocalize(base.startupRefusedBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupTimeoutTitle => pseudoLocalize(base.startupTimeoutTitle);

  @override
  String startupTimeoutBody(String host) =>
      pseudoLocalize(base.startupTimeoutBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupTlsTitle => pseudoLocalize(base.startupTlsTitle);

  @override
  String startupTlsBody(String host) =>
      pseudoLocalize(base.startupTlsBody(pseudoMarker(0)), <String>[host]);

  @override
  String get startupServerErrorTitle =>
      pseudoLocalize(base.startupServerErrorTitle);

  @override
  String startupServerErrorBody(String host, String status) => pseudoLocalize(
    base.startupServerErrorBody(pseudoMarker(0), pseudoMarker(1)),
    <String>[host, status],
  );

  @override
  String get startupInvalidResponseTitle =>
      pseudoLocalize(base.startupInvalidResponseTitle);

  @override
  String startupInvalidResponseBody(String host) => pseudoLocalize(
    base.startupInvalidResponseBody(pseudoMarker(0)),
    <String>[host],
  );

  @override
  String get startupConfigurationTitle =>
      pseudoLocalize(base.startupConfigurationTitle);

  @override
  String get startupConfigurationBody =>
      pseudoLocalize(base.startupConfigurationBody);

  @override
  String get startupStorageTitle => pseudoLocalize(base.startupStorageTitle);

  @override
  String get startupStorageBody => pseudoLocalize(base.startupStorageBody);

  @override
  String get startupUnknownTitle => pseudoLocalize(base.startupUnknownTitle);

  @override
  String get startupUnknownBody => pseudoLocalize(base.startupUnknownBody);

  @override
  String startupServer(String url) =>
      pseudoLocalize(base.startupServer(pseudoMarker(0)), <String>[url]);

  @override
  String startupDetail(String detail) =>
      pseudoLocalize(base.startupDetail(pseudoMarker(0)), <String>[detail]);

  @override
  String startupEnvironment(String name) =>
      pseudoLocalize(base.startupEnvironment(pseudoMarker(0)), <String>[name]);

  @override
  String get startupChangeServer => pseudoLocalize(base.startupChangeServer);

  @override
  String get envDevelopment => pseudoLocalize(base.envDevelopment);

  @override
  String get envStaging => pseudoLocalize(base.envStaging);

  @override
  String get envProduction => pseudoLocalize(base.envProduction);

  @override
  String get envBadgeDevelopment => pseudoLocalize(base.envBadgeDevelopment);

  @override
  String get envBadgeStaging => pseudoLocalize(base.envBadgeStaging);

  @override
  String envBadgeA11y(String name, String host) => pseudoLocalize(
    base.envBadgeA11y(pseudoMarker(0), pseudoMarker(1)),
    <String>[name, host],
  );

  @override
  String get serverTitle => pseudoLocalize(base.serverTitle);

  @override
  String get serverLabel => pseudoLocalize(base.serverLabel);

  @override
  String get serverHelp => pseudoLocalize(base.serverHelp);

  @override
  String serverDefault(String url) =>
      pseudoLocalize(base.serverDefault(pseudoMarker(0)), <String>[url]);

  @override
  String get serverSave => pseudoLocalize(base.serverSave);

  @override
  String get serverReset => pseudoLocalize(base.serverReset);

  @override
  String get serverInvalid => pseudoLocalize(base.serverInvalid);

  @override
  String get serverHttpsRequired => pseudoLocalize(base.serverHttpsRequired);

  @override
  String get serverWrongPath => pseudoLocalize(base.serverWrongPath);

  @override
  String get signInTitle => pseudoLocalize(base.signInTitle);

  @override
  String get signInSubtitle => pseudoLocalize(base.signInSubtitle);

  @override
  String get signInEmailLabel => pseudoLocalize(base.signInEmailLabel);

  @override
  String get signInEmailPlaceholder =>
      pseudoLocalize(base.signInEmailPlaceholder);

  @override
  String get signInPasswordLabel => pseudoLocalize(base.signInPasswordLabel);

  @override
  String get signInPasswordShow => pseudoLocalize(base.signInPasswordShow);

  @override
  String get signInPasswordHide => pseudoLocalize(base.signInPasswordHide);

  @override
  String get signInForgot => pseudoLocalize(base.signInForgot);

  @override
  String get signInSubmit => pseudoLocalize(base.signInSubmit);

  @override
  String get signInLoading => pseudoLocalize(base.signInLoading);

  @override
  String get signInNoAccess => pseudoLocalize(base.signInNoAccess);

  @override
  String get signInErrorRequired => pseudoLocalize(base.signInErrorRequired);

  @override
  String get signInErrorEmailFormat =>
      pseudoLocalize(base.signInErrorEmailFormat);

  @override
  String get signInErrorInvalid => pseudoLocalize(base.signInErrorInvalid);

  @override
  String get signInErrorNoPermission =>
      pseudoLocalize(base.signInErrorNoPermission);

  @override
  String signInErrorThrottled(String time) => pseudoLocalize(
    base.signInErrorThrottled(pseudoMarker(0)),
    <String>[time],
  );

  @override
  String get signInErrorServer => pseudoLocalize(base.signInErrorServer);

  @override
  String get signInOfflineBody => pseudoLocalize(base.signInOfflineBody);

  @override
  String get biometricsTitleFaceId =>
      pseudoLocalize(base.biometricsTitleFaceId);

  @override
  String get biometricsTitleTouchId =>
      pseudoLocalize(base.biometricsTitleTouchId);

  @override
  String get biometricsTitleAndroid =>
      pseudoLocalize(base.biometricsTitleAndroid);

  @override
  String get biometricsBody => pseudoLocalize(base.biometricsBody);

  @override
  String get biometricsEnableFaceId =>
      pseudoLocalize(base.biometricsEnableFaceId);

  @override
  String get biometricsEnableTouchId =>
      pseudoLocalize(base.biometricsEnableTouchId);

  @override
  String get biometricsEnableAndroid =>
      pseudoLocalize(base.biometricsEnableAndroid);

  @override
  String get biometricsNotNow => pseudoLocalize(base.biometricsNotNow);

  @override
  String get biometricsReason => pseudoLocalize(base.biometricsReason);

  @override
  String biometricsPromptSubtitleAndroid(String restaurant) => pseudoLocalize(
    base.biometricsPromptSubtitleAndroid(pseudoMarker(0)),
    <String>[restaurant],
  );

  @override
  String get biometricsFailed => pseudoLocalize(base.biometricsFailed);

  @override
  String get biometricsNotEnrolledFaceId =>
      pseudoLocalize(base.biometricsNotEnrolledFaceId);

  @override
  String get biometricsNotEnrolledTouchId =>
      pseudoLocalize(base.biometricsNotEnrolledTouchId);

  @override
  String get biometricsNotEnrolledAndroid =>
      pseudoLocalize(base.biometricsNotEnrolledAndroid);

  @override
  String get unlockButtonFaceId => pseudoLocalize(base.unlockButtonFaceId);

  @override
  String get unlockButtonTouchId => pseudoLocalize(base.unlockButtonTouchId);

  @override
  String get unlockButtonAndroid => pseudoLocalize(base.unlockButtonAndroid);

  @override
  String get unlockUsePassword => pseudoLocalize(base.unlockUsePassword);

  @override
  String get unlockChanged => pseudoLocalize(base.unlockChanged);

  @override
  String get unlockLockedOut => pseudoLocalize(base.unlockLockedOut);

  @override
  String get unlockPendingCard => pseudoLocalize(base.unlockPendingCard);

  @override
  String get topBarRecent => pseudoLocalize(base.topBarRecent);

  @override
  String topBarMenu(String name) =>
      pseudoLocalize(base.topBarMenu(pseudoMarker(0)), <String>[name]);

  @override
  String get readyAndroidTitle => pseudoLocalize(base.readyAndroidTitle);

  @override
  String get readyAndroidHint => pseudoLocalize(base.readyAndroidHint);

  @override
  String get readyIosButton => pseudoLocalize(base.readyIosButton);

  @override
  String get readyIosHint => pseudoLocalize(base.readyIosHint);

  @override
  String get readyIosTimeout => pseudoLocalize(base.readyIosTimeout);

  @override
  String get readyManual => pseudoLocalize(base.readyManual);

  @override
  String get readyQr => pseudoLocalize(base.readyQr);

  @override
  String get readyFirstCardTipAndroid =>
      pseudoLocalize(base.readyFirstCardTipAndroid);

  @override
  String get readyFirstCardTipIos => pseudoLocalize(base.readyFirstCardTipIos);

  @override
  String get readyNoNfcTitle => pseudoLocalize(base.readyNoNfcTitle);

  @override
  String get readyNoNfcHint => pseudoLocalize(base.readyNoNfcHint);

  @override
  String get readyNoNfcButton => pseudoLocalize(base.readyNoNfcButton);

  @override
  String get readyOfflineTap => pseudoLocalize(base.readyOfflineTap);

  @override
  String get readyOnline => pseudoLocalize(base.readyOnline);

  @override
  String get offlineTitle => pseudoLocalize(base.offlineTitle);

  @override
  String get offlineBody => pseudoLocalize(base.offlineBody);

  @override
  String get maintenanceDefault => pseudoLocalize(base.maintenanceDefault);

  @override
  String get maintenanceDismiss => pseudoLocalize(base.maintenanceDismiss);

  @override
  String get iosSheetAlert => pseudoLocalize(base.iosSheetAlert);

  @override
  String get iosSheetFound => pseudoLocalize(base.iosSheetFound);

  @override
  String get iosSheetReadFailed => pseudoLocalize(base.iosSheetReadFailed);

  @override
  String get iosSheetMultiple => pseudoLocalize(base.iosSheetMultiple);

  @override
  String get iosSheetTimeoutSoon => pseudoLocalize(base.iosSheetTimeoutSoon);

  @override
  String get scanNotCard => pseudoLocalize(base.scanNotCard);

  @override
  String get scanReadFailedTitle => pseudoLocalize(base.scanReadFailedTitle);

  @override
  String get scanReadFailedBody => pseudoLocalize(base.scanReadFailedBody);

  @override
  String get scanDetected => pseudoLocalize(base.scanDetected);

  @override
  String get scanLookingUp => pseudoLocalize(base.scanLookingUp);

  @override
  String get scanSlow => pseudoLocalize(base.scanSlow);

  @override
  String get scanUnavailable => pseudoLocalize(base.scanUnavailable);

  @override
  String get balanceCardOverline => pseudoLocalize(base.balanceCardOverline);

  @override
  String balanceCardValidUntil(String date) => pseudoLocalize(
    base.balanceCardValidUntil(pseudoMarker(0)),
    <String>[date],
  );

  @override
  String get balanceCardNoExpiry => pseudoLocalize(base.balanceCardNoExpiry);

  @override
  String balanceCardMasked(String last4) =>
      pseudoLocalize(base.balanceCardMasked(pseudoMarker(0)), <String>[last4]);

  @override
  String balanceCardA11y(
    String restaurant,
    String spokenAmount,
    String last4,
  ) => pseudoLocalize(
    base.balanceCardA11y(pseudoMarker(0), pseudoMarker(1), pseudoMarker(2)),
    <String>[restaurant, spokenAmount, last4],
  );

  @override
  String chargeCardNumberA11y(String number) => pseudoLocalize(
    base.chargeCardNumberA11y(pseudoMarker(0)),
    <String>[number],
  );

  @override
  String get a11yChargeClose => pseudoLocalize(base.a11yChargeClose);

  @override
  String a11yAmount(String spokenAmount) =>
      pseudoLocalize(base.a11yAmount(pseudoMarker(0)), <String>[spokenAmount]);

  @override
  String get chargeEnterAmount => pseudoLocalize(base.chargeEnterAmount);

  @override
  String chargeRedeem(String amount) =>
      pseudoLocalize(base.chargeRedeem(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeRedeemFull(String amount) =>
      pseudoLocalize(base.chargeRedeemFull(pseudoMarker(0)), <String>[amount]);

  @override
  String get chargeHold => pseudoLocalize(base.chargeHold);

  @override
  String get a11yHoldHint => pseudoLocalize(base.a11yHoldHint);

  @override
  String chargeRedeeming(String amount) =>
      pseudoLocalize(base.chargeRedeeming(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeOverBalance(String diff) =>
      pseudoLocalize(base.chargeOverBalance(pseudoMarker(0)), <String>[diff]);

  @override
  String a11yOverBalance(String diff) =>
      pseudoLocalize(base.a11yOverBalance(pseudoMarker(0)), <String>[diff]);

  @override
  String chargeUseBalance(String amount) =>
      pseudoLocalize(base.chargeUseBalance(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeUseMax(String amount) =>
      pseudoLocalize(base.chargeUseMax(pseudoMarker(0)), <String>[amount]);

  @override
  String chargeMaxSingle(String amount) =>
      pseudoLocalize(base.chargeMaxSingle(pseudoMarker(0)), <String>[amount]);

  @override
  String get chargeFullOnly => pseudoLocalize(base.chargeFullOnly);

  @override
  String get chargeVelocityTitle => pseudoLocalize(base.chargeVelocityTitle);

  @override
  String chargeVelocityBodyTime(int minutes) =>
      pseudoLocalize(base.chargeVelocityBodyTime(minutes), <String>[]);

  @override
  String chargeRateLimited(int seconds) =>
      pseudoLocalize(base.chargeRateLimited(seconds), <String>[]);

  @override
  String get chargeSwitchCardMessage =>
      pseudoLocalize(base.chargeSwitchCardMessage);

  @override
  String get chargeSwitchCardAction =>
      pseudoLocalize(base.chargeSwitchCardAction);

  @override
  String get chargeSwitchCardKeep => pseudoLocalize(base.chargeSwitchCardKeep);

  @override
  String get chargeSwitchCardDialogTitle =>
      pseudoLocalize(base.chargeSwitchCardDialogTitle);

  @override
  String get keypadDoubleZero => pseudoLocalize(base.keypadDoubleZero);

  @override
  String get keypadDelete => pseudoLocalize(base.keypadDelete);

  @override
  String get keypadDeleteHint => pseudoLocalize(base.keypadDeleteHint);

  @override
  String get keypadCleared => pseudoLocalize(base.keypadCleared);

  @override
  String get keypadMaxReached => pseudoLocalize(base.keypadMaxReached);

  @override
  String get badgeActive => pseudoLocalize(base.badgeActive);

  @override
  String get badgeInactive => pseudoLocalize(base.badgeInactive);

  @override
  String get badgeRedeemed => pseudoLocalize(base.badgeRedeemed);

  @override
  String get badgeBlocked => pseudoLocalize(base.badgeBlocked);

  @override
  String get badgeExpired => pseudoLocalize(base.badgeExpired);

  @override
  String get badgeReplaced => pseudoLocalize(base.badgeReplaced);

  @override
  String get cardBlocked => pseudoLocalize(base.cardBlocked);

  @override
  String cardBlockedReason(String reason) =>
      pseudoLocalize(base.cardBlockedReason(pseudoMarker(0)), <String>[reason]);

  @override
  String get cardExpired => pseudoLocalize(base.cardExpired);

  @override
  String cardExpiredBody(String date) =>
      pseudoLocalize(base.cardExpiredBody(pseudoMarker(0)), <String>[date]);

  @override
  String get cardInactive => pseudoLocalize(base.cardInactive);

  @override
  String get cardInactiveBody => pseudoLocalize(base.cardInactiveBody);

  @override
  String get cardReplaced => pseudoLocalize(base.cardReplaced);

  @override
  String get cardReplacedBody => pseudoLocalize(base.cardReplacedBody);

  @override
  String get cardEmpty => pseudoLocalize(base.cardEmpty);

  @override
  String get cardEmptyBody => pseudoLocalize(base.cardEmptyBody);

  @override
  String get redeemSlow => pseudoLocalize(base.redeemSlow);

  @override
  String get uncertainTitle => pseudoLocalize(base.uncertainTitle);

  @override
  String get uncertainBody => pseudoLocalize(base.uncertainBody);

  @override
  String uncertainRetrying(int n) =>
      pseudoLocalize(base.uncertainRetrying(n), <String>[]);

  @override
  String get uncertainGuestHint => pseudoLocalize(base.uncertainGuestHint);

  @override
  String get uncertainFailedBody => pseudoLocalize(base.uncertainFailedBody);

  @override
  String get uncertainCancelled => pseudoLocalize(base.uncertainCancelled);

  @override
  String get uncertainCancelledGuestHint =>
      pseudoLocalize(base.uncertainCancelledGuestHint);

  @override
  String redeemBalanceChanged(String amount) => pseudoLocalize(
    base.redeemBalanceChanged(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get redeemTapAgain => pseudoLocalize(base.redeemTapAgain);

  @override
  String get successTitle => pseudoLocalize(base.successTitle);

  @override
  String successRemaining(String amount) =>
      pseudoLocalize(base.successRemaining(pseudoMarker(0)), <String>[amount]);

  @override
  String get successEmpty => pseudoLocalize(base.successEmpty);

  @override
  String get successNextIos => pseudoLocalize(base.successNextIos);

  @override
  String get successNextAndroid => pseudoLocalize(base.successNextAndroid);

  @override
  String get successShowGuest => pseudoLocalize(base.successShowGuest);

  @override
  String successCard(String last4) =>
      pseudoLocalize(base.successCard(pseudoMarker(0)), <String>[last4]);

  @override
  String get guestRemainingLabel => pseudoLocalize(base.guestRemainingLabel);

  @override
  String a11ySuccess(String amount, String balance) => pseudoLocalize(
    base.a11ySuccess(pseudoMarker(0), pseudoMarker(1)),
    <String>[amount, balance],
  );

  @override
  String get problemNotFoundTitle => pseudoLocalize(base.problemNotFoundTitle);

  @override
  String get problemNotFoundBody => pseudoLocalize(base.problemNotFoundBody);

  @override
  String get problemNotFoundBodyManual =>
      pseudoLocalize(base.problemNotFoundBodyManual);

  @override
  String get problemForeignTitle => pseudoLocalize(base.problemForeignTitle);

  @override
  String get problemForeignBody => pseudoLocalize(base.problemForeignBody);

  @override
  String get problemVerifyTitle => pseudoLocalize(base.problemVerifyTitle);

  @override
  String get problemVerifyBody => pseudoLocalize(base.problemVerifyBody);

  @override
  String get problemThrottledTitle =>
      pseudoLocalize(base.problemThrottledTitle);

  @override
  String get problemThrottledBody => pseudoLocalize(base.problemThrottledBody);

  @override
  String problemScanAgainIn(String time) =>
      pseudoLocalize(base.problemScanAgainIn(pseudoMarker(0)), <String>[time]);

  @override
  String get problemNetworkBody => pseudoLocalize(base.problemNetworkBody);

  @override
  String get problemServerTitle => pseudoLocalize(base.problemServerTitle);

  @override
  String get problemServerBody => pseudoLocalize(base.problemServerBody);

  @override
  String get manualTitle => pseudoLocalize(base.manualTitle);

  @override
  String get manualHelper => pseudoLocalize(base.manualHelper);

  @override
  String manualCounter(int count) =>
      pseudoLocalize(base.manualCounter(count), <String>[]);

  @override
  String get manualSubmit => pseudoLocalize(base.manualSubmit);

  @override
  String get manualErrorInvalid => pseudoLocalize(base.manualErrorInvalid);

  @override
  String get manualErrorPaste => pseudoLocalize(base.manualErrorPaste);

  @override
  String get qrTitle => pseudoLocalize(base.qrTitle);

  @override
  String get qrHint => pseudoLocalize(base.qrHint);

  @override
  String get qrNotCard => pseudoLocalize(base.qrNotCard);

  @override
  String get qrDark => pseudoLocalize(base.qrDark);

  @override
  String get qrTorchOn => pseudoLocalize(base.qrTorchOn);

  @override
  String get qrTorchOff => pseudoLocalize(base.qrTorchOff);

  @override
  String get qrManual => pseudoLocalize(base.qrManual);

  @override
  String get recentTitle => pseudoLocalize(base.recentTitle);

  @override
  String recentSummary(int count, String amount) => pseudoLocalize(
    base.recentSummary(count, pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String recentRowRemaining(String amount) => pseudoLocalize(
    base.recentRowRemaining(pseudoMarker(0)),
    <String>[amount],
  );

  @override
  String get recentRowEmpty => pseudoLocalize(base.recentRowEmpty);

  @override
  String recentRowA11y(
    String time,
    String last4,
    String amount,
    String balance,
  ) => pseudoLocalize(
    base.recentRowA11y(
      pseudoMarker(0),
      pseudoMarker(1),
      pseudoMarker(2),
      pseudoMarker(3),
    ),
    <String>[time, last4, amount, balance],
  );

  @override
  String get recentEmptyTitle => pseudoLocalize(base.recentEmptyTitle);

  @override
  String get recentEmptyBody => pseudoLocalize(base.recentEmptyBody);

  @override
  String get recentFooter => pseudoLocalize(base.recentFooter);

  @override
  String get recentLimit => pseudoLocalize(base.recentLimit);

  @override
  String get recentDetailTitle => pseudoLocalize(base.recentDetailTitle);

  @override
  String get recentDetailTime => pseudoLocalize(base.recentDetailTime);

  @override
  String get recentDetailCard => pseudoLocalize(base.recentDetailCard);

  @override
  String get recentDetailAmount => pseudoLocalize(base.recentDetailAmount);

  @override
  String get recentDetailRemaining =>
      pseudoLocalize(base.recentDetailRemaining);

  @override
  String get recentDetailTransaction =>
      pseudoLocalize(base.recentDetailTransaction);

  @override
  String get recentDetailSupportCode =>
      pseudoLocalize(base.recentDetailSupportCode);

  @override
  String get recentDetailReverseHint =>
      pseudoLocalize(base.recentDetailReverseHint);

  @override
  String get menuClose => pseudoLocalize(base.menuClose);

  @override
  String get menuAccount => pseudoLocalize(base.menuAccount);

  @override
  String get menuRestaurant => pseudoLocalize(base.menuRestaurant);

  @override
  String get menuDevice => pseudoLocalize(base.menuDevice);

  @override
  String get menuSectionSettings => pseudoLocalize(base.menuSectionSettings);

  @override
  String get menuTheme => pseudoLocalize(base.menuTheme);

  @override
  String get menuThemeSystem => pseudoLocalize(base.menuThemeSystem);

  @override
  String get menuThemeLight => pseudoLocalize(base.menuThemeLight);

  @override
  String get menuThemeDark => pseudoLocalize(base.menuThemeDark);

  @override
  String get menuSunlightTip => pseudoLocalize(base.menuSunlightTip);

  @override
  String get menuSound => pseudoLocalize(base.menuSound);

  @override
  String get menuHaptics => pseudoLocalize(base.menuHaptics);

  @override
  String get menuHapticsUnavailable =>
      pseudoLocalize(base.menuHapticsUnavailable);

  @override
  String get menuKeepScreenOn => pseudoLocalize(base.menuKeepScreenOn);

  @override
  String get menuKeepScreenOnCaption =>
      pseudoLocalize(base.menuKeepScreenOnCaption);

  @override
  String get menuHelp => pseudoLocalize(base.menuHelp);

  @override
  String menuVersion(String version) =>
      pseudoLocalize(base.menuVersion(pseudoMarker(0)), <String>[version]);

  @override
  String get menuSignOut => pseudoLocalize(base.menuSignOut);

  @override
  String get menuSignOutConfirmTitle =>
      pseudoLocalize(base.menuSignOutConfirmTitle);

  @override
  String get menuSignOutConfirmBody =>
      pseudoLocalize(base.menuSignOutConfirmBody);

  @override
  String get menuSignOutConfirmAction =>
      pseudoLocalize(base.menuSignOutConfirmAction);

  @override
  String get sessionExpired => pseudoLocalize(base.sessionExpired);

  @override
  String get sessionExpiredBody => pseudoLocalize(base.sessionExpiredBody);

  @override
  String get sessionExpiredAction => pseudoLocalize(base.sessionExpiredAction);

  @override
  String get forbiddenTitle => pseudoLocalize(base.forbiddenTitle);

  @override
  String get forbiddenBody => pseudoLocalize(base.forbiddenBody);

  @override
  String get deviceRevokedTitle => pseudoLocalize(base.deviceRevokedTitle);

  @override
  String get deviceRevokedBody => pseudoLocalize(base.deviceRevokedBody);

  @override
  String get deviceRevokedAction => pseudoLocalize(base.deviceRevokedAction);

  @override
  String get suspendedTitle => pseudoLocalize(base.suspendedTitle);

  @override
  String get suspendedBody => pseudoLocalize(base.suspendedBody);

  @override
  String get lockedTitle => pseudoLocalize(base.lockedTitle);

  @override
  String lockedBody(String time) =>
      pseudoLocalize(base.lockedBody(pseudoMarker(0)), <String>[time]);

  @override
  String lockedButton(String time) =>
      pseudoLocalize(base.lockedButton(pseudoMarker(0)), <String>[time]);

  @override
  String get lockedOver => pseudoLocalize(base.lockedOver);

  @override
  String get deactivatedTitle => pseudoLocalize(base.deactivatedTitle);

  @override
  String get deactivatedBody => pseudoLocalize(base.deactivatedBody);

  @override
  String get updateTitle => pseudoLocalize(base.updateTitle);

  @override
  String get updateBody => pseudoLocalize(base.updateBody);

  @override
  String get updateAction => pseudoLocalize(base.updateAction);

  @override
  String get nfcOffTitle => pseudoLocalize(base.nfcOffTitle);

  @override
  String get nfcOffBody => pseudoLocalize(base.nfcOffBody);

  @override
  String get nfcOffAction => pseudoLocalize(base.nfcOffAction);

  @override
  String get nfcOffOn => pseudoLocalize(base.nfcOffOn);

  @override
  String get cameraDeniedTitle => pseudoLocalize(base.cameraDeniedTitle);

  @override
  String get cameraDeniedBody => pseudoLocalize(base.cameraDeniedBody);

  @override
  String get cameraDeniedAction => pseudoLocalize(base.cameraDeniedAction);

  @override
  String get cameraRestrictedBody => pseudoLocalize(base.cameraRestrictedBody);

  @override
  String get cameraUnavailableTitle =>
      pseudoLocalize(base.cameraUnavailableTitle);

  @override
  String get cameraUnavailableBody =>
      pseudoLocalize(base.cameraUnavailableBody);

  @override
  String get introSkip => pseudoLocalize(base.introSkip);

  @override
  String get introNext => pseudoLocalize(base.introNext);

  @override
  String get introStart => pseudoLocalize(base.introStart);

  @override
  String introPage(int n) => pseudoLocalize(base.introPage(n), <String>[]);

  @override
  String get intro1TitleAndroid => pseudoLocalize(base.intro1TitleAndroid);

  @override
  String get intro1BodyAndroid => pseudoLocalize(base.intro1BodyAndroid);

  @override
  String get intro1TitleIos => pseudoLocalize(base.intro1TitleIos);

  @override
  String get intro1BodyIos => pseudoLocalize(base.intro1BodyIos);

  @override
  String get intro1TitleNoNfc => pseudoLocalize(base.intro1TitleNoNfc);

  @override
  String get intro1BodyNoNfc => pseudoLocalize(base.intro1BodyNoNfc);

  @override
  String get intro2Title => pseudoLocalize(base.intro2Title);

  @override
  String intro2Body(String threshold) =>
      pseudoLocalize(base.intro2Body(pseudoMarker(0)), <String>[threshold]);

  @override
  String get intro3Title => pseudoLocalize(base.intro3Title);

  @override
  String get intro3Body => pseudoLocalize(base.intro3Body);

  @override
  String a11ySpokenAmount(int euros, String cents) => pseudoLocalize(
    base.a11ySpokenAmount(euros, pseudoMarker(0)),
    <String>[cents],
  );

  @override
  String a11yCardLoaded(String restaurant, String spokenAmount) =>
      pseudoLocalize(
        base.a11yCardLoaded(pseudoMarker(0), pseudoMarker(1)),
        <String>[restaurant, spokenAmount],
      );

  @override
  String a11yProblem(String title, String body) => pseudoLocalize(
    base.a11yProblem(pseudoMarker(0), pseudoMarker(1)),
    <String>[title, body],
  );

  @override
  String get a11yReady => pseudoLocalize(base.a11yReady);

  @override
  String get a11yScanAvailable => pseudoLocalize(base.a11yScanAvailable);

  @override
  String get a11yRedeemAvailable => pseudoLocalize(base.a11yRedeemAvailable);
}
