<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\NotificationLog;
use App\Services\Exports\CsvExporter;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Tests\TestCase;

/**
 * Exports page through the table by primary key. A row whose id is out of step with the order the caller asked for
 * (ids are generated by PHP, created_at by the database; two waiters booking in the same second) must appear exactly
 * once — a payments export that drops or doubles a row is a wrong cash-up.
 */
final class CsvExportPagingTest extends TestCase
{
    public function test_every_row_is_exported_exactly_once_whatever_order_the_query_asks_for(): void
    {
        config(['giftcard.exports.chunk_size' => 2]);
        $ids = [];
        // Ids ascending, created_at descending: the opposite orders.
        foreach (range(1, 7) as $i) {
            $id = sprintf('00000000-0000-7000-8000-%012d', $i);
            $ids[] = $id;
            $log = new NotificationLog(['template_key' => 'voucher_issued', 'channel' => 'mail', 'recipient' => "r{$i}@example.test", 'status' => 'sent']);
            $log->id = $id;
            $log->created_at = Carbon::parse('2026-10-01 12:00:00')->subMinutes($i);
            $log->save();
        }

        $response = app(CsvExporter::class)->stream(
            NotificationLog::query()->orderBy('created_at'),
            ['Id' => static fn (NotificationLog $l): string => $l->id],
            'test.csv',
        );
        ob_start();
        $response->sendContent();
        $csv = (string) ob_get_clean();

        $rows = array_slice(array_filter(explode("\n", $csv), static fn (string $l): bool => Str::of($l)->trim()->isNotEmpty()), 1);
        sort($rows);
        $this->assertSame($ids, array_values($rows));
    }
}
