#!/bin/sh
# ---------------------------------------------------------------------------
# GiftCard Pro API container entrypoint. One image, four roles (CONTAINER_ROLE):
#
#   migrate    one-shot: APP_KEY (first deploy), migrations, reference data → exits 0
#   app        php-fpm on :9000 (behind the gateway)
#   worker     queue worker
#   scheduler  cron replacement (schedule:work)
#
# docker-compose.coolify.yml starts "migrate" first; app, worker and scheduler only
# start after it finished successfully, so no process ever sees an unmigrated schema.
# ---------------------------------------------------------------------------
set -eu
cd /var/www/html
ROLE="${CONTAINER_ROLE:-app}"

fail() { echo "[entrypoint:$ROLE] ERROR: $*" >&2; exit 1; }
log() { echo "[entrypoint:$ROLE] $*"; }

# --- Public URL --------------------------------------------------------------
# Coolify sets SERVICE_URL_GATEWAY (with scheme) / SERVICE_FQDN_GATEWAY (without) from the
# domain configured for the gateway service. An explicit APP_URL wins.
url="${APP_URL:-}"
[ -n "$url" ] || url="${SERVICE_URL_GATEWAY:-}"
if [ -z "$url" ] && [ -n "${SERVICE_FQDN_GATEWAY:-}" ]; then url="https://${SERVICE_FQDN_GATEWAY}"; fi
url="${url%%,*}"      # several domains: the first one is canonical
url="${url%/}"
if [ -n "$url" ]; then
  case "$url" in http://*|https://*) ;; *) url="https://$url" ;; esac
  host="${url#*://}"; host="${host%%/*}"; hostname="${host%%:*}"
  export APP_URL="$url"
  export FRONTEND_URL="${FRONTEND_URL:-$url}"
  export CARD_BASE_URL="${CARD_BASE_URL:-$url}"
  export SESSION_DOMAIN="${SESSION_DOMAIN:-$hostname}"
  export SANCTUM_STATEFUL_DOMAINS="${SANCTUM_STATEFUL_DOMAINS:-$host}"
  export MAIL_FROM_ADDRESS="${MAIL_FROM_ADDRESS:-no-reply@$hostname}"
else
  fail "No public URL. Assign a domain to the 'gateway' service in Coolify (e.g. https://app.giftcardpro.at) or set APP_URL."
fi

# --- Secrets generated by Coolify ---------------------------------------------
[ -n "${DB_PASSWORD:-}" ] || fail "DB_PASSWORD is empty — Coolify should generate SERVICE_PASSWORD_MYSQL. Check the Environment Variables of this resource."
[ -n "${REDIS_PASSWORD:-}" ] || fail "REDIS_PASSWORD is empty — Coolify should generate SERVICE_PASSWORD_REDIS. Check the Environment Variables of this resource."

# --- APP_KEY -------------------------------------------------------------------
# Set APP_KEY in Coolify to manage it yourself. Otherwise the first deploy generates one and
# keeps it in the persistent storage volume (shared by all Laravel containers), so it survives
# every redeploy. Losing it logs everybody out and makes encrypted values unreadable.
KEY_FILE=storage/app/.app-key
if [ -z "${APP_KEY:-}" ]; then
  if [ ! -s "$KEY_FILE" ]; then
    if [ "$ROLE" = "migrate" ]; then
      umask 077
      php -r 'echo "base64:".base64_encode(random_bytes(32));' > "$KEY_FILE"
      log "Generated APP_KEY and stored it in the storage volume ($KEY_FILE). Back it up (see docs/DEPLOYMENT.md)."
    else
      i=0
      while [ ! -s "$KEY_FILE" ] && [ "$i" -lt 30 ]; do sleep 2; i=$((i + 1)); done
      [ -s "$KEY_FILE" ] || fail "APP_KEY missing: neither set in Coolify nor created by the migrate service."
    fi
  fi
  APP_KEY="$(cat "$KEY_FILE")"
  export APP_KEY
fi

# --- Roles ---------------------------------------------------------------------
case "$ROLE" in
  migrate)
    # --isolated takes a cache lock (Redis): two deployments can never migrate at the same time.
    php artisan migrate --force --isolated --no-interaction
    php artisan db:seed --class='Database\Seeders\RolesAndPermissionsSeeder' --force --no-interaction
    php artisan db:seed --class='Database\Seeders\NotificationTemplateSeeder' --force --no-interaction
    php artisan db:seed --class='Database\Seeders\SystemSettingsSeeder' --force --no-interaction
    log "Database is up to date."
    exit 0
    ;;
  app|worker|scheduler)
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    php artisan event:cache
    exec "$@"
    ;;
  *)
    fail "Unknown CONTAINER_ROLE '$ROLE' (migrate, app, worker, scheduler)."
    ;;
esac
